### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by smorenitez** [ading2210/edpuzzle-answers#27]
it doesnt let me skip the video or show answers and theres a 403 error in console
![image](https://github.com/ading2210/edpuzzle-answers/assets/152504256/5dc50e63-6aba-408f-832d-d74042f7f93c)

**Comment by smorenitez** [comment]
Pls fix it I have an edpuzzle due Monday

**Comment by xmstack** [comment]
Same think it got patched

**Comment by smorenitez** [comment]
FIX IT BRO

**Comment by smorenitez** [comment]
@ading2210 FIX ITTTTTTTTTTTTTTTTTTTTTTTTTTTTT

**Comment by Lolbozo30207** [comment]
It still doesent work lol

**Comment by Lolbozo30207** [comment]
fixed?

**Comment by smorenitez** [comment]
of course it’s not fixed because he’s a lazy piece of shit lmao

**Comment by wearrrrr** [comment]
dude stfu, you aren't entitled to anything. How about you do YOUR schoolwork, you're the one being a lazy piece of shit here.

**Comment by RyanFu008** [comment]
sounds like a skill issue!!!

**Comment by smorenitez** [comment]
this project has been broken for what, 4 months already? there is no excuse. he is willingly choosing not to work on it.

**Comment by TheMemeSniper** [comment]
![image](https://github.com/ading2210/edpuzzle-answers/assets/67394719/64a710a8-c6bd-41f3-892f-df7a4071aa84)

**Comment by wearrrrr** [comment]
> this project has been broken for what, 4 months already? there is no excuse. he is willingly choosing not to work on it.

Okay? Open source developers don't owe you fucking anything. You didn't pay for this, so why should you expect them to work on something completely for free so you can be academically dishonest?

**Comment by TheMemeSniper** [comment]
> this project has been broken for what, 4 months already? there is no excuse. he is willingly choosing not to work on it.

if it's so easy to "fix it" why don't you make a fork, implement your fix and make a pull request

**Comment by smorenitez** [comment]
> if it's so easy to "fix it" why don't you make a fork, implement your fix and make a pull request

Bud, I literally code free projects. I know the ins and outs of API requests. I know how to make a newer, more modern, and more better version of what BS this project is. But I am choosing not to because I am not going to waste my energy because of some developer who cant even spend his energy, 4 hours of his life at most, to code an update. No way that is happening. I already have a barebones patch to the new update, but it's private for a reason. I'm protesting against lazy development like this,

Also @wearrrrr  I don't care. I have a right to be mad about lazy development teams like this. Imagine if ur favorite game company decided to never update it again and it kept saying "If you want updates so bad make them yourself and make a pull request" Cuz thats how ur looking like right now.

**Comment by TheMemeSniper** [comment]
okay so what you're saying is that this issue can be closed

**Comment by wearrrrr** [comment]
> > if it's so easy to "fix it" why don't you make a fork, implement your fix and make a pull request
> 
> Bud, I literally code free projects. I know the ins and outs of API requests. I know how to make a newer, more modern, and more better version of what BS this project is. But I am choosing not to because I am not going to waste my energy because of some developer who cant even spend his energy, 4 hours of his life at most, to code an update. No way that is happening. I already have a barebones patch to the new update, but it's private for a reason. I'm protesting against lazy development like this,
> 
> Also @wearrrrr  I don't care. I have a right to be mad about lazy development teams like this. Imagine if ur favorite game company decided to never update it again and it kept saying "If you want updates so bad make them yourself and make a pull request" Cuz thats how ur looking like right now.

For someone who "doesn't care", you really are caring a lot right now. They have better stuff to do then listen to whiny assholes like you complain. Also, using bud just makes you sound incredibly cringy, gtfo of here.

**Comment by wearrrrr** [comment]
Also congrats on the new copypasta ;)

**Comment by smorenitez** [comment]
@TheMemeSniper No because there are like half a millon people who are relying on this project for edpuzzles like this used to get thousands of executions of the js a day but now its 0 cuz its broken and hes too lazy to add afucking update and i am not going to publish my **private** code just because of a lazy developer who is probably gonna steal it cuz its "open source" and @wearrrrr Ur just speaking nonsense bro like what better stuff are they doing, playing basketball with friends or something?? Thats doing nothing for the thousands who used this project every day for edpuzzles, lil bro.

**Comment by TheMemeSniper** [comment]
bro does not understand the open source philosophy

**Comment by CoolElectronics** [comment]
if you're so much better do it yourself lol

**Comment by ProgrammerIn-wonderland** [comment]
The whole mercury workshop is here

**Comment by ProgrammerIn-wonderland** [comment]
> @ading2210 FIX ITTTTTTTTTTTTTTTTTTTTTTTTTTTTT 

Yikes you're acting like an entitled child

**Comment by wearrrrr** [comment]
> what better stuff are they doing

How about working on the protocol for a web proxy? How about porting libcurl to the browser? How about working on projects that they actual enjoy working on? Refer to my previous messages where I tell you that open source developers owe you NOTHING. I, and ading probably do not give two shits about the "thousands of people" that use this project. If you're going to reply to me, please make it make sense..

**Comment by Endercass** [comment]
> @TheMemeSniper No because there are like half a millon people who are relying on this project for edpuzzles like this used to get thousands of executions of the js a day but now its 0 cuz its broken and hes too lazy to add afucking update and i am not going to publish my **private** code just because of a lazy developer who is probably gonna steal it cuz its "open source" and @wearrrrr Ur just speaking nonsense bro like what better stuff are they doing, playing basketball with friends or something?? Thats doing nothing for the thousands who used this project every day for edpuzzles, lil bro.

you autistic fucking monkey

**Comment by ProgrammerIn-wonderland** [comment]
> of course it’s not fixed because he’s a lazy piece of shit lmao
Like, super entitled

**Comment by ProgrammerIn-wonderland** [comment]
> this project has been broken for what, 4 months already? there is no excuse. he is willingly choosing not to work on it.

Extremely entitled

**Comment by ProgrammerIn-wonderland** [comment]
> > if it's so easy to "fix it" why don't you make a fork, implement your fix and make a pull request
> 
> Bud, I literally code free projects. I know the ins and outs of API requests. I know how to make a newer, more modern, and more better version of what BS this project is. But I am choosing not to because I am not going to waste my energy because of some developer who cant even spend his energy, 4 hours of his life at most, to code an update. No way that is happening. I already have a barebones patch to the new update, but it's private for a reason. I'm protesting against lazy development like this,
> 
> Also @wearrrrr  I don't care. I have a right to be mad about lazy development teams like this. Imagine if ur favorite game company decided to never update it again and it kept saying "If you want updates so bad make them yourself and make a pull request" Cuz thats how ur looking like right now.

And no you don't

**Comment by wearrrrr** [comment]
For the record, saying thousands of people rely on this is incredibly stupid, because the repo has just over 150 stars.

**Comment by ProgrammerIn-wonderland** [comment]
I suspect there may be a barrier of intelligence between everyone else in this conversation and @smorenitez, he may not be understanding what we are saying

**Comment by miikart** [comment]
> > if it's so easy to "fix it" why don't you make a fork, implement your fix and make a pull request
> 
> Bud, I literally code free projects. I know the ins and outs of API requests. I know how to make a newer, more modern, and more better version of what BS this project is. But I am choosing not to because I am not going to waste my energy because of some developer who cant even spend his energy, 4 hours of his life at most, to code an update. No way that is happening. I already have a barebones patch to the new update, but it's private for a reason. I'm protesting against lazy development like this,
> 
> Also @wearrrrr I don't care. I have a right to be mad about lazy development teams like this. Imagine if ur favorite game company decided to never update it again and it kept saying "If you want updates so bad make them yourself and make a pull request" Cuz thats how ur looking like right now.

🐋

**Comment by genericness** [comment]
> > if it's so easy to "fix it" why don't you make a fork, implement your fix and make a pull request
> 
> Bud, I literally code free projects. I know the ins and outs of API requests. I know how to make a newer, more modern, and more better version of what BS this project is. But I am choosing not to because I am not going to waste my energy because of some developer who cant even spend his energy, 4 hours of his life at most, to code an update. No way that is happening. I already have a barebones patch to the new update, but it's private for a reason. I'm protesting against lazy development like this,
> 
> Also @wearrrrr I don't care. I have a right to be mad about lazy development teams like this. Imagine if ur favorite game company decided to never update it again and it kept saying "If you want updates so bad make them yourself and make a pull request" Cuz thats how ur looking like right now.

just do your edpuzzle yourself bruh, vk6 isn't being paid 

he ain't required to do shit for your lousy ass

so shut the fuck up and go do your fucking homework yourself

**Comment by BomberFish** [comment]
holy shit this thread is actually golden

**Comment by ProgrammerIn-wonderland** [comment]
Wait a second... Your underage aren't you, you were looking for iready "hacks" on GitHub

**Comment by AverageJuliet** [comment]
:skull: i have not heard of iready since like 2nd grade

**Comment by wearrrrr** [comment]
whenever you guys quote reply can you leave out the @ for me, I'd prefer to not be spammed by all the quote replies 😭

**Comment by BomberFish** [comment]
@smorenitez 
> Thats doing nothing for the thousands who used this project every day for edpuzzles, lil bro.

Who do you think you are man :sob:

**Comment by ProgrammerIn-wonderland** [comment]
Nah, you're a part of this now, touhou kid

**Comment by genericness** [comment]
> Wait a second... Your underage aren't you, you were looking for iready "hacks" on GitHub

so real

**Comment by Riftriot** [comment]
> @TheMemeSniper No because there are like half a millon people who are relying on this project for edpuzzles like this used to get thousands of executions of the js a day but now its 0 cuz its broken and hes too lazy to add afucking update and i am not going to publish my **private** code just because of a lazy developer who is probably gonna steal it cuz its "open source" and @wearrrrr Ur just speaking nonsense bro like what better stuff are they doing, playing basketball with friends or something?? Thats doing nothing for the thousands who used this project every day for edpuzzles, lil bro.

"Private code" LOL. Sure bud.

One of the most overused, overhyped, least meaningful and most non-specific terms in this github issue today.

And how many students and devs (really, devs that barely put enough effort into their own projects so that they can use?) are going to dev for the necessary APIs? YOU?? "Private code?" really? lol.

**Comment by AverageJuliet** [comment]
bad apple...

**Comment by kxtzownsu** [comment]
According to your profile history, you were looking for i-Ready hacks. I-Ready is for students in grades KG-8, this means that you are either underage OR on the very edge of being underage 😭 

@smorenitez

**Comment by AverageJuliet** [comment]
bud really wants that automated iready script

**Comment by wearrrrr** [comment]
> Nah, you're a part of this now, touhou kid

noooo

**Comment by genericness** [comment]
> bad apple...

hazbin hotel season 2 when
![image](https://github.com/ading2210/edpuzzle-answers/assets/107654710/efdf4035-5c7c-4e4a-88c4-8a6818f71353)

**Comment by ProgrammerIn-wonderland** [comment]
Not s good look for someone who is barely legally allowed to use GitHub..

**Comment by wearrrrr** [comment]
> According to your profile history, you were looking for i-Ready hacks. I-Ready is for students in grades KG-8, this means that you are either underage OR on the very edge of being underage 😭
> 
> @smorenitez

it's so funny how bro stopped replying after he realized we knew

**Comment by genericness** [comment]
> bud really wants that automated iready script

blud cant spend 15 minutes on his homework

**Comment by BomberFish** [comment]
> > if it's so easy to "fix it" why don't you make a fork, implement your fix and make a pull request
> 
> Bud, I literally code free projects. I know the ins and outs of API requests. I know how to make a newer, more modern, and more better version of what BS this project is. But I am choosing not to because I am not going to waste my energy because of some developer who cant even spend his energy, 4 hours of his life at most, to code an update. No way that is happening. I already have a barebones patch to the new update, but it's private for a reason. I'm protesting against lazy development like this,
> 
> Also @wearrrrr I don't care. I have a right to be mad about lazy development teams like this. Imagine if ur favorite game company decided to never update it again and it kept saying "If you want updates so bad make them yourself and make a pull request" Cuz thats how ur looking like right now.

My man, your "protest" looks stupid as hell. If you want it so badly and clearly have the skills, why don't you do it yourself? :trollface:

**Comment by ProgrammerIn-wonderland** [comment]
Man GitHub issues being realtime makes this so much hetterv

**Comment by kxtzownsu** [comment]
real

**Comment by genericness** [comment]
> Man GitHub issues being realtime makes this so much better

so real

**Comment by AverageJuliet** [comment]
![image](https://github.com/ading2210/edpuzzle-answers/assets/134985726/5b066086-488b-4e56-be10-05b24902c3ad)

this you? @smorenitez

**Comment by interpolation-0** [comment]
@smorenitez you are literally underage

you were looking for iready hacks (which is designed for k-8)

and additionally you asked why the code was obfuscated,
while you whine about not sharing your private code because you dont want it "stolen"

**Comment by genericness** [comment]
> @smorenitez you are literally underage
> 
> you were looking for iready hacks (which is designed for k-8)
> 
> and additionally you asked why the code was obfuscated, while you whine about not sharing your private code because you dont want it "stolen"

skid alert

**Comment by AverageJuliet** [comment]
*vine boom*

**Comment by BomberFish** [comment]
its actually funny the moment this got posted in tn the issue just blew up

**Comment by interpolation-0** [comment]
your **private code** probably does not exist

**Comment by genericness** [comment]
> your **private code** probably does not exist



> _vine boom_

poison hazbin hotel reference?

**Comment by AverageJuliet** [comment]
![image](https://github.com/ading2210/edpuzzle-answers/assets/134985726/2ddb1c5d-ac52-4121-bf8e-6b3c7d079d34)

**Comment by wearrrrr** [comment]
> bad apple...

流れてく　時の中ででも　気だるさが　ほらグルグル廻って
私から　離れる心も　見えないわ　そう知らない？
自分から　動くこともなく　時の隙間に　流され続けて
知らないわ　周りのことなど　私は私　それだけ

**Comment by BomberFish** [comment]
> @smorenitez you are literally underage
> 
> you were looking for iready hacks (which is designed for k-8)
> 
> and additionally you asked why the code was obfuscated, while you whine about not sharing your private code because you dont want it "stolen"

to be fair 8th graders can be 13 but that's besides the point

**Comment by ading2210** [comment]
For an actual explanation as to why this is so hard to fix:

![image](https://github.com/ading2210/edpuzzle-answers/assets/71154407/98cd5342-b778-4587-8184-2f854981d5e8)
